=begin
#API Référentiels géographiques

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0-beta

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.5

=end

require 'spec_helper'
require 'json'

# Unit tests for ApiGeoClient::DpartementsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'DpartementsApi' do
  before do
    # run before each test
    @instance = ApiGeoClient::DpartementsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DpartementsApi' do
    it 'should create an instance of DpartementsApi' do
      expect(@instance).to be_instance_of(ApiGeoClient::DpartementsApi)
    end
  end

  # unit tests for departements_code_communes_get
  # Renvoi les communes d&#39;un département
  # @param code Code du département
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :fields Liste des champs souhaités dans la réponse
  # @option opts [String] :format Format de réponse attendu
  # @option opts [String] :geometry Géométrie à utiliser pour la sortie géographique
  # @return [Commune]
  describe 'departements_code_communes_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for departements_code_get
  # Récupérer les informations concernant un département
  # @param code Code du département
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :fields Liste des champs souhaités dans la réponse
  # @return [Departement]
  describe 'departements_code_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for departements_get
  # Recherche des départements
  # @param [Hash] opts the optional parameters
  # @option opts [String] :code Code du département
  # @option opts [String] :code_region Code région associé
  # @option opts [String] :nom Nom du département
  # @option opts [Array<String>] :fields Liste des champs souhaités dans la réponse
  # @return [Array<Departement>]
  describe 'departements_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for regions_code_departements_get
  # Renvoi les départements d&#39;une région
  # @param code Code de la région
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :fields Liste des champs souhaités dans la réponse
  # @return [Departement]
  describe 'regions_code_departements_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
