=begin
#API Référentiels géographiques

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0-beta

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.5

=end

# Common files
require 'api_geo_client/api_client'
require 'api_geo_client/api_error'
require 'api_geo_client/version'
require 'api_geo_client/configuration'

# Models
require 'api_geo_client/models/commune'
require 'api_geo_client/models/departement'
require 'api_geo_client/models/error'
require 'api_geo_client/models/region'

# APIs
require 'api_geo_client/api/communes_api'
require 'api_geo_client/api/dpartements_api'
require 'api_geo_client/api/rgions_api'

module ApiGeoClient
  class << self
    # Customize default settings for the SDK using block.
    #   ApiGeoClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
